Non-blocking functions
melexis/mlx90632-library pull request #50
Opened 2024-05-02 01:05 UTC by adnan-ashraf

Provided functions enabling non-blocking operation (closes #49)

2024-08-05 19:22 UTC, adnan-ashraf commented
Can someone please review this pull request? @Letme

2024-08-05 20:22 UTC, Letme requested changes
Nice contribution. Thanks for the effort. I just have few stylistic requests.

Sorry it took so long, I must have missed this somehow.

2024-08-05 20:22 UTC, Letme commented on src/mlx90632.c
> +    int tries = MLX90632_MAX_NUMBER_MESUREMENT_READ_TRIES;
lets arrange variables in inverted xmass tree:

```suggestion
    int tries = MLX90632_MAX_NUMBER_MESUREMENT_READ_TRIES;
    uint16_t reg_status;
    int32_t ret;
```

2024-08-05 20:22 UTC, Letme commented on src/mlx90632.c
> +    int tries = MLX90632_MAX_NUMBER_MESUREMENT_READ_TRIES;
```suggestion
    int tries = MLX90632_MAX_NUMBER_MESUREMENT_READ_TRIES;
    uint16_t reg_status;
    int32_t ret;
```

2024-08-05 20:22 UTC, Letme commented on src/mlx90632.c
> +    uint16_t reg;
```suggestion
    uint16_t reg;
    int32_t ret;
```

2024-08-05 20:22 UTC, Letme commented on src/mlx90632.c
> +    uint16_t reg_status;
```suggestion
    uint16_t reg_status;
    int32_t ret;
```

2024-08-05 20:26 UTC, Letme commented
Ok, now CI is also running. Can I ask you to also add some tests for your changes, to make sure we do not break anything (and that we did not break anything now)?

2024-08-05 20:32 UTC, Letme commented
Regarding CI: I need to fix master, but I am waiting for Ceedling 1.0.0 release (this current version in master is fairly close to the 1.0.0, so it should be easy). That means that currently unit tests are not running as we are referencing non-existing pre-release https://github.com/ThrowTheSwitch/Ceedling/releases

2024-08-06 10:11 UTC, adnan-ashraf commented
Thanks for taking the time to review!

Appreciate the feedback! Your suggestions have been added.

Sure, I'll write the tests.

2024-08-08 04:38 UTC, yogeshiggalore commented
when this will get merged..?

2024-08-08 06:36 UTC, Letme commented
As soon as some tests are added to maintain functionality. I will do a local run with a latest pre-release to make sure that after fix of CI we have all green checks.

Before for some reason CI was not run on external pull requests, but now we fixed this. The only problem is that Ceedling did not release 1.0.0 version yet.

2024-08-08 15:44 UTC, adnan-ashraf commented
I've added the unit tests, please review the changes.

I was able to run the tests successfully only when I changed `0UL` to `0ULL` in `GENMASK` definition, or by changing `BITS_PER_LONG` to `32` in project.yml file. Should we create another issue and pull request to fix `GENMASK` definition, or should I go ahead with the fix in this branch? Please suggest!

2024-08-08 19:30 UTC, adnan-ashraf commented
I've fixed the `GENMASK` definition making it independent of `BITS_PER_LONG`, and also fixed some other issues. In addition, I've also improved the tests code. Please review the changes and provide any feedback, thanks!

2024-08-09 10:04 UTC, Letme commented
Can you also run stylechecker, as it seems uncrusitfy complains about something?

2024-08-09 10:12 UTC, Letme approved these changes
Thanks for the complete contribution. I do not have the environment ready to do a complete temperature range check, I will rely on your and my manual tests. Once I fix ceedling with released gem also the CI will maintain the quality.
I think stylechecker complains about a line length, but that should be a quick run fix and then we merge.

2024-08-09 10:45 UTC, adnan-ashraf commented on inc/mlx90632.h
> +    ((((1U << h) - 1) | (1U << h)) & ~((1U << l) - 1))
Tested and worked on both 32-bits and 64-bits based systems

2024-08-09 11:11 UTC, adnan-ashraf commented
I've run uncrustify, so the stylechecker is working successfully now!

2024-08-09 11:44 UTC, adnan-ashraf commented
I'm sorry that stylechecker is complaining again. I used uncrustify latest version 0.79.0 and it locally ran successfully. The stylechecker workflow is using uncrustify version 0.75.1. This could be the reason of failure.

2024-08-09 12:22 UTC, adnan-ashraf commented
I've updated the stylechecker to use the latest version of uncrustify. I think, it shouldn't complain now. Thanks!

2024-08-09 13:10 UTC, merged

2024-08-09 13:11 UTC, Letme commented
Great. Newer uncrustify is also one less worry for me to update. Thanks for the initiative.

2024-08-09 19:11 UTC, adnan-ashraf commented
Glad to hear, happy to help!